services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - minio
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data/raw:/opt/airflow/data/raw
      # Mount our custom init script
      - ./airflow/scripts/entrypoint.sh:/entrypoint.sh:ro
    # Run that script as the container’s entrypoint
    entrypoint: ["/bin/bash", "/entrypoint.sh"]