  # ...existing code...
services:
  
  # Initialize Airflow variables
  airflow-init-variables:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init-variables
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow:/opt/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow variables import /opt/airflow/variables.json || echo 'Variables already exist or import failed' &&
        echo 'Variables initialization complete!'
      "
    depends_on:
      - postgres
    restart: "no"
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      - minio
      - airflow-init-variables
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - ACTUALDATA_POSTGRES_HOST=actualdata-postgres
      - ACTUALDATA_POSTGRES_PORT=5432
      - ACTUALDATA_POSTGRES_USER=actualdata
      - ACTUALDATA_POSTGRES_PASSWORD=actualdata_pass
      - ACTUALDATA_POSTGRES_DB=actualdata
      - MB_HOSTNAME=metabase
      - MB_PORT=3000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./scoring/scripts:/opt/airflow/scoring/scripts
      - ./scoring/scripts:/app/scoring/scripts
      - ./scoring:/opt/airflow/scoring
      - ./scoring:/app/scoring
      - ./metabase:/opt/airflow/metabase
      - ./data/raw:/opt/airflow/data/raw
      - ./data/processed:/opt/airflow/data/processed
      - ./helpers:/opt/airflow/helpers
      # Mount our custom init script
      - ./airflow/scripts/entrypoint.sh:/entrypoint.sh:ro
      - ./visualizations:/opt/airflow/visualizations
    # Run that script as the container’s entrypoint
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  actualdata-postgres:
    image: postgres:15
    container_name: actualdata-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: actualdata
      POSTGRES_PASSWORD: actualdata_pass
      POSTGRES_DB: actualdata
    ports:
      - "5436:5432"
    volumes:
      - actualdata_postgres_data:/var/lib/postgresql/data
    depends_on:
      - airflow

  metabase-postgres:
    image: postgres:15
    container_name: metabase-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_pass
      POSTGRES_DB: metabase
    ports:
      - "5435:5432"
    volumes:
      - metabase_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${METABASE_POSTGRES_USER} -h ${METABASE_POSTGRES_HOST} -p ${METABASE_POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
      image: metabase/metabase:latest
      platform: linux/arm64/v8
      container_name: metabase
      depends_on:
        metabase-postgres:
          condition: service_healthy
      ports:
        - "3000:3000"
      env_file:
        - .env
      environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME:  metabase
        MB_DB_PORT: 5432
        MB_DB_USER: metabase
        MB_DB_PASS: metabase_pass
        MB_DB_HOST: metabase-postgres
        MB_SETUP_ADMIN_EMAIL: admin@metabase.local
        MB_SETUP_ADMIN_PASSWORD: metabaseadminpass
        MB_SETUP_ADMIN_FIRST_NAME: Admin
        MB_SETUP_ADMIN_LAST_NAME: User

volumes:
  postgres_data:
  metabase_postgres_data:
  actualdata_postgres_data: