version: 2

sources:
  - name: fraud_data
    description: "Raw and processed fraud detection data stored in MinIO (S3-compatible) as Parquet files. Used as the source layer for all downstream transformations."
    meta:
      external_location: "read_parquet('s3://fraud-data-processed/{name}/**/*.parquet')"
    tables:
      - name: customers
        description: "Customer master data, including account creation, demographics, and home device/IP/location."

      - name: transactions
        description: "All financial transactions, including amounts, timestamps, merchant, and customer references."

      - name: merchants
        description: "Merchant reference data, including merchant category, risk score, and location."
        
      - name: login_attempts
        description: "Customer login attempts, including timestamps, device, IP, and success/failure status."