version: 2

sources:
  - name: fraud_data
    meta:
        external_location: "read_parquet('s3://fraud-data-processed/{name}/**/*.parquet')"
    tables:
      - name: customers
      - name: transactions
      - name: merchants
      - name: login_attempts