version: 2

sources:
  - name: fraud_detection
    schema: 'customers'  # No schema for direct S3 access
    meta:
        external_location: "read_parquet('s3://fraud-data-processed/customers/**/*.parquet')"
    tables:
      - name: customers
        description: "Customer data from MinIO"